POST localhost:8000/api/v1/check/payment
Content-Type: application/json

{
  "address": "bcrt1p8wk52jm0zv77l4etxmnlng0tgvc989p9xj9lwzv8zs7q20zdd7cqu6mg89",
  "webhook_url": "http://localhost:50051/check/payment?id=5183e945-5785-4119-bc76-b423e45b3042"
}